name: npm_publish

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout # step name
              uses: actions/checkout@v2 # action name

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - name: cache npm packages
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: npm-packages-v1-${{ hashFiles('package-lock.json') }}

            - name: npm install
              run: npm install

            - name: check npm versions
              run: npx can-npm-publish --verbose # publish可能なversionかチェック
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_GENERATE_TOKEN }}

            - name: build
              run: npm build

            - name: publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_GENERATE_TOKEN }}
